### ISSUE TITLE
Windows: Failed to install symlink

### ISSUE THREAD

**Issue by mkody** [keys-pub/app#14]
I tried to install it and at its first run, I get this.  
v0.0.39 downloaded from the releases, Windows 10 Pro 1903.  
With the command line I get the `timed out waiting for pid` message too.

![image](https://user-images.githubusercontent.com/843787/81418885-ab429c00-914d-11ea-9517-d965a708889f.png)

**Comment by gabriel** [comment]
Thanks for submitting the issue, sorry it isn't working for you.

You said you installed the command line, was this via scoop?

If you run `keysd` does it show an error?

(You may need to run `keys stop` to stop an existing keysd if it is already running.)

**Comment by graphixillusion** [comment]
Same error for me too. Windows 10 1909, installed from msi downloaded from the website.

**Comment by mkody** [comment]
Yes I installed the CLI from scoop. Running `keysd` returns me this

```
PS C:\Users\mkody> keysd
time="2020-05-08T23:50:25.7056157+02:00" level=info msg="Version: 0.0.39 fa25a4ec201c3ceaafbc7add19751e72df2ce505 2020-05-05T22:22:26Z"
time="2020-05-08T23:50:25.9016157+02:00" level=info msg="Log level: info"
time="2020-05-08T23:50:25.9036171+02:00" level=info msg="Keyring (default)"
time="2020-05-08T23:50:25.9036171+02:00" level=info msg="Keyring, using wincred"
Élément introuvable.
```

**Comment by gabriel** [comment]
I'm having trouble reproducing on my windows machine.. Is there anything non standard about your window install that might cause the windows credential API to not be available?

**Comment by graphixillusion** [comment]
@gabriel is there any other way to check if Windows Credential API is working correctly?

**Comment by gabriel** [comment]
Oh you know, maybe antivirus software is preventing that. Do you mind sharing which antivirus software you might have?

**Comment by graphixillusion** [comment]
@gabriel i'm using the Windows built in, Windows Defender

**Comment by gabriel** [comment]
Oh wait.. does it fail if you have both scoop and the app installed?

**Comment by gabriel** [comment]
There might be 2 issues here... A wincred issue and a scoop+app conflict issue.

**Comment by mkody** [comment]
On my side, it was already happening with the app only.
I don't have anything other than the Windows Defender on my machine too. 

Except enabling the Linux subsystem and having docker running, I think I did much to my Windows.

**Comment by graphixillusion** [comment]
Yep, the error occurs with the only app installed (with msi, not the cmdline version by scoop)

**Comment by gabriel** [comment]
@graphixillusion @mkody what happens if you run `keysd.exe`?

(keysd is in `~/AppData/Local/Programs/keys/resources/bin`)

**Comment by gabriel** [comment]
If you have go installed can you run this:

```shell
go get github.com/keys-pub/keys/keyring/cmd/keyring
`go env GOPATH`/bin/keyring
```

This will list your keyring IDs... does this throw an error?

**Comment by graphixillusion** [comment]
@gabriel keysd output:

```
time="2020-05-10T03:38:37.8293049+02:00" level=info msg="Version: 0.0.43 22cc59110c810f4707e26f11908c729c51e8e06f 2020-05-09T21:24:41Z"
time="2020-05-10T03:38:38.1411127+02:00" level=info msg="Log level: info"
time="2020-05-10T03:38:38.1421119+02:00" level=info msg="Keyring (default)"
time="2020-05-10T03:38:38.1431106+02:00" level=info msg="Keyring, using wincred"
Unable to find element.
```

**Comment by gabriel** [comment]
I figured it out, fix coming soon.

**Comment by gabriel** [comment]
This should be fixed in https://github.com/keys-pub/app/releases/tag/v0.0.45.

It was an i18n issue... the wincred package was checking error strings insread of codes, so was failing on non-english locales, see https://github.com/keys-pub/wincred/pull/1 for more details.

So @graphixillusion it was totally a language related error, you called it :)

I had to install a French version of Windows to reproduce (an English version with French language packs though wouldn't reproduce).

Anyway thanks for helping out.
