### ISSUE TITLE
Reddit Linking - Username starts with special character 

### ISSUE THREAD

**Issue by caffeine-1** [keys-pub/app#15]
My reddit username begins with a "-", which makes is incompatible.

![Screenshot_20200509_165545](https://user-images.githubusercontent.com/30202047/81487068-1f954200-9217-11ea-9ba5-27a240cd7a48.png)

**Comment by gabriel** [comment]
Bold choice for a username :)

Yeah we can update the Reddit user check to match what Reddit itself accepts.

Thanks for submitting an issue.

**Comment by gabriel** [comment]
This should be fixed in v0.0.45.
