### ISSUE TITLE
Back button leads to being stuck on blank screen

### ISSUE THREAD

**Issue by mrsegen** [keys-pub/app#16]
On Windows, version 0.0.47 (after upgrade from 0.0.45), after signing in, when the upper left corner back arrow is clicked, all content disappears from the window with no way of returning. Workaround: close the program and reopen.

**Comment by gabriel** [comment]
Fixed in https://github.com/keys-pub/app/commit/94aa9e1564d13c5a794b9f56b2a2bc569a739272. 
Thanks for the bug report.
