### ISSUE TITLE
Twitter linking broken?

### ISSUE THREAD

**Issue by Deozaan** [keys-pub/app#18]
I generated keys for Twitter last month. But today when I tried to sign something using that key, they key was in red and wouldn't verify it.

I tried telling the Keys desktop app to update my Twitter link, but it kept saying it couldn't find the content. Unsure of what I was doing wrong, I revoked the key and tried linking a new one with a new post to my Twitter account, but Keys still says `user check failed: user signed message content not found` even though [it's definitely there and public on my Twitter account](https://twitter.com/Deozaan/status/1276308498242916352).

It was working last month in 0.0.45, but today I downloaded an update to 0.0.47. Unfortunately I didn't check to verify that it was still working before I installed the update.

It seems to force the username to lowercase even though my username is capitalized. But I'm not sure if that is related to the problem I'm having. See https://github.com/keys-pub/keys/issues/30 as a potentially related issue.

This is on Windows 10.

**Comment by gabriel** [comment]
Yeah twitter verification broke in 0.0.45 and 0.0.47 update fixed that. It also fixed some issues around case sensitivity and special characters in user names. If you had verified a username with uppercase characters in a previous version unfortunately you'll have to revoke and re-link using the latest version of the app.

You've already done this a few times, probably is frustrating, sorry about that. Have you tried to revoke and re-link your twitter account using the latest version 0.0.47? What happens is it should allow you to use capitalization but when the user statement is signed and indexed in search it is normalized (to lowercase). 

If you continue to have problems, lmk and I'll investigate further. Thanks for reporting your issues, things are still verify much in "beta", so your feedback is super helpful.

**Comment by Deozaan** [comment]
> Have you tried to revoke and re-link your twitter account using the latest version 0.0.47?

Yes, I am attempting this in 0.0.47 and it isn't working for me.

**Comment by gabriel** [comment]
Hmm, it's possible the old invalid statement is preventing the sigchain for verifying. Can you try with a brand new key?

**Comment by Deozaan** [comment]
Yes, I tried that already and it has the same behavior.

**Comment by gabriel** [comment]
Ahh, ok I am able to reproduce it right now. I think something changed on twitters API, I'll have to investigate it further.

Sorry for the run around, I was having trouble reproducing.

**Comment by gabriel** [comment]
Twitter is doing redirects on case changes (either this changed recently or I missed it when testing last release).

On verification, I am allowing a redirect if the URLs are the case-insensitive equal.
https://github.com/keys-pub/keys/pull/94

This will go in the next release. I am going to do a pre-release build in a bit, I'll let you know

**Comment by gabriel** [comment]
Pre-release with fix here: https://github.com/keys-pub/app/releases/tag/v0.0.48

**Comment by Deozaan** [comment]
I can confirm that linking with Twitter works in v0.0.48. 👍 

Thanks!
