### ISSUE TITLE
GUI should provide encrypt-to-self option in encrypt page or in prefs

### ISSUE THREAD

**Issue by grempe** [keys-pub/app#29]
It is a common use case to encrypt a message to someone, but desire to retain the ability to decrypt the file yourself at a later time as well.

Currently, you can do this in the GUI by adding one or more of your own keys to the recipient list.

There should be an option (perhaps on the encrypt tool page, or perhaps in the preferences, to always encrypt all files to self as well. I suppose this would require allowing preference setter to also choose which key(s) to always encrypt to by default.

If you don't remember to do this now, if you paste encrypted text into the decrypt tool you get a red error `no decryption key found for message` which may not be interpreted by less sophisticated users as "You don't have any of the private keys required to decrypt this message. Perhaps add yourself as a recipient?"

Screenshot:

https://share.getcloudapp.com/2NuykQBx

**Comment by gabriel** [comment]
The latest version will add the sender as a recipient (unless toggled off).

![2020-09-04 at 3 12 PM](https://user-images.githubusercontent.com/2669/92288294-59bed980-eec1-11ea-97d3-e896126fa498.png)

I'll probably add in a warning or description that explains exactly how it is being encrypted like:

"This can be decrypted by gabriel@github, gabriel@echo and is signed by gabriel@echo."
or
"You won't be able to decrypt this message without adding one of your keys as a recipient."
