### ISSUE TITLE
Doesn't respect macOS DNS resolvers

### ISSUE THREAD

**Issue by brandonkal** [keys-pub/app#46]
When I launched the app, my firewall alerted me that Keys was trying to contact 1.1.1.1, an IP given by DHCP. However, a quick
```
scutil --dns
```
reveals that this is not my number 1 resolver and Keys should instead be using 192.0.2.42 in my particular case.

Given the nature of this program, this should respect OS preferences over whatever the router hands out.

**Comment by gabriel** [comment]
The app doesn't do anything special with dns, this could be an issue or behavior with the golang runtime itself?

**Comment by brandonkal** [comment]
Good to know. I'll have to test to see how the golang runtime behaves.

**Comment by gabriel** [comment]
Out of curiosity, when is a secondary DNS is supposed to be used? Is it only in case the primary is down, or is it allowed to cycle through? Also could a DNS packet drop randomly and just happens to use the secondary one time? Maybe we'll never know :)
