### ISSUE TITLE
linux: App fails on startup

### ISSUE THREAD

**Issue by devsnek** [keys-pub/app#6]
I'm using Linux xone 5.6.7-arch1-1 SMP PREEMPT x86_64 GNU/Linux

![](https://gc.gy/55812361.png)

**Comment by gabriel** [comment]
Currently the linux build requires gnome-keyring. I'm working on supporting without, but may be a week or so before that lands.

**Comment by terrywang** [comment]
AppImage is great (prefer it over `flatpak` or `snap`), good jobs guys.

I like the idea of keys, Keybase has drifted away and lost the initial goal as crypto for human beings, becoming something collaborative and social lol.

Back to business, same problem when running it on Manjaro and Arch Linux (I don't use GNOME but KDE, lxqt and other WM).

Error
```bash
Oops, exec error: Error: Command Failed: /tmp/.mount_Keys-05nNviU/-resources/bin/keys start --from=app
timeout waiting for pid 
```
Don't assume GNOME Shell the default Desktop Environment for Linux ;-)

Thanks for looking into it @gabriel .

**Comment by terrywang** [comment]
Update: Just tried `0.0.38`, issue persists.

**Comment by gabriel** [comment]
Fixed https://github.com/keys-pub/keysd/commit/4676afdcaee89356988d20e53e75b27e65d7bd5a

See https://github.com/keys-pub/app/releases/tag/v0.0.39-rc1
