### ISSUE TITLE
GitHub linking: name should be lowercase

### ISSUE THREAD

**Issue by TheLastProject** [keys-pub/app#9]
![image](https://user-images.githubusercontent.com/1885159/81324715-a6231580-9097-11ea-8eef-6c6243d722bd.png)

Seeing how GitHub shows usernames with capitalisation (but allows logging in with any case), this should probably be quietly converted to lowercase internally as it can be confusing for people like me who are used to logging in with a specific capitalisation.

This seems like a very issue issue for someone new to take up. So if you agree to this change, I am willing to make a pull request for it.

**Comment by TheLastProject** [comment]
![image](https://user-images.githubusercontent.com/1885159/81325230-585add00-9098-11ea-9577-0dee60b541a1.png)

Seems the whole (GitHub) workflow suffers from this minor UX issue.

**Comment by gabriel** [comment]
Thanks for the bug report! 

I think I can accept different case on input and lowercase them either from the client when submitting or in the service, but it will still appear lowercase in search which I think is ok at least for now.

**Comment by gabriel** [comment]
Latest builds should have this fixed.
